### ISSUE TITLE
Missing ./stage/geographic_information.tsv file

### ISSUE THREAD

**Issue by Adrianzo** [abeconnelly/untap#24]
I run `public-database-snapshot` with no problems, but I'm unable to create the sqlite file...

```
➜  untap git:(master) ✗ ./scripts/export_surveys_to_sqlite3.py ./stage/untap.db ./stage
Traceback (most recent call last):
  File "./scripts/export_surveys_to_sqlite3.py", line 133, in <module>
    populate_table(curs, table, ifn)
  File "./scripts/export_surveys_to_sqlite3.py", line 112, in populate_table
    with open(fn, "r") as fp:
IOError: [Errno 2] No such file or directory: './stage/geographic_information.tsv'
```

How do I grab this missing file? Couldn't even find it manually at http://www.personalgenomes.org/harvard/data

Thanks!

**Comment by Adrianzo** [comment]
Any clues?

**Comment by abeconnelly** [comment]
@Adrianzo, I ran this on my local system without an issue, though I didn't check in depth.

My suspicion is that the error reporting isn't that in depth and there might be a hidden dependency that is causing one of the sub scripts to work on my system but fail on yours.  The error catching isn't the best so it's pretty possible that an error occurs in a sub script and doesnt' get properly propagated upwards.  My suggestions would be to do the following:

* Make sure you have [pup](https://github.com/ericchiang/pup) and [jq](https://stedolan.github.io/jq/) installed.  This is used for some processing of the scraped HTML files and might be why some part of the process is failing.
* Check to make sure all the data you expect to be there is in the staging directories.  There is obviously one data file that isn't there and that's why it's failing (the `geographic_information.tsv`) but maybe you can figure out which other ones are missing or are 0 length to trace back where the failure started.
* Run each of the steps from `public-database-snapshot` individually to make sure they succeed and create the expected files.

If you want, you can try to paste the `stage` directory listing here to see if I can't pick out what's missing.  If you want to show whatever other state the `untap` download and staging directories are in, that might also help.

One of the reasons the `untap` script takes so long is because it's scraping each participant's profile.  If you limit the number of profiles scraped by only taking the first few huIDs in the `scratch/hid.list` file, that should speed testing up.  You have to make sure the script itself doesn't overwrite the `hid.list` file, so doing something like adding a line around https://github.com/abeconnelly/untap/blob/master/public-database-snapshot#L44 that says something like:

```
  head -n 10 scratch/hid.list > scratch/test_hid.list
  mv scratch/test_hid.list scratch/hid.list
```

or even commenting out line https://github.com/abeconnelly/untap/blob/master/public-database-snapshot#L43 and using your own `scratch/hid.list` file that has the first 10 huIDs or so.

I hope that helps.  Let me know how it goes.

**Comment by Adrianzo** [comment]
Thanks a lot, sorry I've been away for a few days. Now **this** problem seems to be solved with the lastest commit you've made. Anyway, I've just made a **test run** and here's the last lines of output:

> Done grabbing enrollment date data.
> inserting into untap.db
> downloading report data
> ./public-database-snapshot: line 117: ./generate: No such file or directory

Maybe you forgot to commit that script file?

**Comment by Adrianzo** [comment]
Thanks a lot, now it's solved with your latest commit.
